-include ../makefile.$(OS)
-include ../Makefile.Local
-include Makefile.Local

MCU = atmega2560
PMCU = atmega2560
FORMAT = ihex
PROGRAMMER = wiring
TARGET_NAME = host

-include ../Makefile.Shared