-include ../makefile.$(OS)
-include ../Makefile.Local
-include Makefile.Local

MCU = attiny2313
PMCU = t2313
FORMAT = ihex
PROGRAMMER = dragon_isp
TARGET_NAME = controller

-include ../Makefile.Shared